flags:
extra-package-dbs: []
packages:
- '.'
- ../PL
- ../PLGrammar
- ../PLParser
- ../PLPrinter
- ../PLLabel
- ../Reversible
- location:
    git: https://github.com/syallop/DSL-Compose.git
    commit: 8e49641f049c586e21c36c6982f51670082e1e3f
  extra-dep: true
extra-deps:
- megaparsec-6.4.0
- parser-combinators-0.4.0
resolver: lts-9.18
