resolver: lts-14.20
flags:
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/syallop/PL
    commit: 528db1a8918270a7c8c1c8107494ec05a0b02d8c
  extra-dep: true
- location:
    git: https://github.com/syallop/PLParser
    commit: 7adea4ba5ec67f7fee80f9903595e1ab825e313b
  extra-dep: true
- location:
    git: https://github.com/syallop/PLGrammar
    commit: f9d8ae7019c5fb3c25f7122f0e9c29fd1cb71fbc
  extra-dep: true
- location:
    git: https://github.com/syallop/Reversible
    commit: 5185a10559f0567ba927ea67a0b90f446d87dbe3
  extra-dep: true
- location:
    git: https://github.com/syallop/PLLabel
    commit: 9433cf7963e43b4df06f57939218956c3d2dacc4
  extra-dep: true
- location:
    git: https://github.com/syallop/PLPrinter
    commit: 65f4d3805c06fbbe0e4313f17a2129e5fe2187f9
  extra-dep: true
- location:
    git: https://github.com/syallop/DSL-Compose.git
    commit: 8e49641f049c586e21c36c6982f51670082e1e3f
  extra-dep: true
extra-deps:
- megaparsec-7.0.4
- parser-combinators-1.0.1
allow-newer: true
