resolver: lts-13.1
flags:
extra-package-dbs: []
packages:
- '.'
- ../PL
- ../PLGrammar
- ../PLParser
- ../PLPrinter
- ../PLLabel
- ../Reversible
- location:
    git: https://github.com/syallop/DSL-Compose.git
    commit: 8e49641f049c586e21c36c6982f51670082e1e3f
  extra-dep: true
extra-deps:
- megaparsec-7.0.4
- parser-combinators-1.0.1
allow-newer: true
